### ISSUE TITLE
Docker image doesn't work in the Kubeflow 1.7 release; UI is blank

### ISSUE THREAD

**Issue by jlewi** [jlewi/roboweb-docs#30]
Reported in [kubeflow-discuss](https://groups.google.com/g/kubeflow-discuss/c/J5TWiR1RCLk)
Here's a screenshot
![image](https://user-images.githubusercontent.com/777219/233505970-08319e72-5f16-47f4-995c-28f649276a62.png)

I don't have Kubeflow deployed right now so I can't try to reproduce this. When I use the image  (us-west1-docker.pkg.dev/roboweb-images/roboweb-images/kubeflow/jupyterlab) on my K8s cluster it works.  Here would be a couple of things to try to debug the issue

1. Try to launch the notebook using the [simple manifests](https://github.com/jlewi/roboweb-docs/tree/main/k8s/manifests) provided in this repository. If that works, then it suggests the Kubeflow notebook controller is setting environment variables or other configuration that prevents the jupyter lab extension from loading

1. When using Kubeflow a notebook and accessing the extension, open the chrome developers tab to see if there are any errors

1. Inside the Kubeflow notebook image run 
    
    ```
    jupyter lab path  
    ```

**Comment by franciscouribe** [comment]
I don't think it's worthwhile to keep investing in debugging the extension. we should pivot to build a hosted version instead where we can control the environment and focus on model quality

**Comment by johnugeorge** [comment]
<img width="951" alt="Screenshot 2023-04-21 at 2 55 23 PM" src="https://user-images.githubusercontent.com/2171903/233599833-9c0dc053-719b-470f-8297-946d37a8fae8.png">

**Comment by jlewi** [comment]
I wasn't able to reproduce this using the Kubeflow notebook controller 1.7. 

I deployed the KF notebook controller in standalone mode and then ran a container.

```
apiVersion: v1
items:
- apiVersion: kubeflow.org/v1
  kind: Notebook
  metadata:
    annotations:
    name: kf-test
    namespace: notebooks
  spec:
    template:
      spec:
        containers:
        - image: us-west1-docker.pkg.dev/roboweb-images/roboweb-images/kubeflow/jupyterlab:latest
          name: my-notebook
```

I port-forwarded to the notebook.

@johnugeorge Were you port-forwarding to the notebook or accessing the notebook through some gateway? 

The log indicates its trying to download "main.dart.js". It would be useful to check the network tab in the developer console to see if there is an error downloading that asset. I suspect there could be an issue when running behind a reverse proxy.
